### ISSUE TITLE
Not seeing "Node" field in block

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/node_property_block#2]
Based upon your comment in Zulip, I'm expecting to see this field (this is a screenshot of your screenshot):

![image](https://user-images.githubusercontent.com/3144571/192942309-18fa6d03-4680-4827-a829-ff1aa00adf58.png)

BUT, I create a layout with these settings:

![image](https://user-images.githubusercontent.com/3144571/192942385-7142e941-2342-4485-9153-09edaff6f461.png)

I then add a Node Property block and I only see this:

![image](https://user-images.githubusercontent.com/3144571/192942459-71d81c7b-1762-4dbd-b067-78784e5f1bc0.png)

Atten: @argiepiano

**Comment by argiepiano** [comment]
@stpaultim the reason you are not seeing that node selection field is that you ONLY have one node in context. The block (just like ALL other node-related blocks) assumes that you are referring to the node in position 2 automatically. There is no other node to select from in the context.

If you want to see that selection field, then you need to manually add another node in the context. 

Other than that, did you actually test the module? Did it not do what's expected?

Please reopen if there is an actual bug.

**Comment by stpaultim** [comment]
@argiepiano - Yes, I tested the module. Which is how I found this situation. I reported what I thought was a bug, because what I was seeing didn't reflect the screenshots you were sharing and I was concerned that I might not be seeing everything this module is capable of.

Glad to realize it was not a bug, although I still don't understand why. By this, I mean that I don't understand what having two nodes in the context means or how I would manually add another node in the context for testing. 

But, it does matter. Yes, the module is working for me and I think it's a GREAT module. Thank you for doing this.

**Comment by argiepiano** [comment]
I'll be glad to explain. 

A layout with a path of `node/%` has only one node in the context (the one specified by the % in position 2 of the path).

You can always add another node in the context by going to Configure Layout and clicking + Add context. Then selecting Node and adding a node ID. See images below.

So, the selection box ONLY appears if you have MORE than one node in the context. If you only have one node (for example the one specified by node/%) then that selection box will not appear. This BTW is how the Layout blocks work - it's not just this particular module.

<img width="1008" alt="Screen Shot 2022-09-29 at 8 48 59 PM" src="https://user-images.githubusercontent.com/9938978/193179562-a9d2b9c1-921f-47c9-a476-888959d56c4b.png">

<img width="675" alt="Screen Shot 2022-09-29 at 8 49 05 PM" src="https://user-images.githubusercontent.com/9938978/193179571-99fae614-2a10-4bbb-aa3a-c1655a7d48a2.png">

**Comment by stpaultim** [comment]
@argiepiano - Thanks. Your explanation is helpful. 

For some reason, I have had some difficulty wrapping my head around certain aspects of the layouts system including contexts. But, thanks to both you and @bugfolder (who has done a lot to help make the layout system more understandable), I'm getting there.

**Comment by stpaultim** [comment]
@argiepiano - Even better, I used your instructions to put another node into context and after seeing it in action, it makes even more sense. Sometimes, I have to do things myself (walk through the steps) before I fully understand them.

**Comment by argiepiano** [comment]
That's great! Yes, there is nothing like hands-on learning. At times the lingo used by these functionalities is more confusing than it should (what does "context" mean in this context? Wouldn't it be easier to call these "attachments" or "attached nodes"?)
