### ISSUE TITLE
Author / Date Format

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/node_property_block#3]
@argiepiano - Thanks so much for creating this module. I see that there is some interest in getting this into core, but in the meantime it's really great to have this module available. 

This is part feature request and/or simple question. I believe that this came up in Zulip already. 

I think it would be great to be able to place the "Authored by" data as formated in the content type config in a block. 

![image](https://user-images.githubusercontent.com/3144571/193181832-cda3fc74-32cc-4536-a0dc-34023db5a5f5.png)

Is this something that would make sense in this module OR does it not make sense, because the data in that format is something other than a property of the node? (If so, what is it?)

I understand, that one can recreate this information and format with the [Token Block](https://backdropcms.org/project/token_block) module (thanks for that one as well). But, it would be nice to have the data in the content type specified format available, without having to rebuild it. 

I believe that @kswan asked for the same thing already.

If this is out of scope of this module. I understand.

**Comment by argiepiano** [comment]
This feature has been added to the next release.
